image:
  dockerfile: Dockerfile.ci

build_image:
  tags:
    - docker
  image:
    dockerfile: Dockerfile.ci

#  script:
#    - mkdir -p ../build
#    - cd ../build
#    - cmake ../likelib
#    - make -j 4

