#image: ubuntu:19.10
#  dockerfile: Dockerfile.ci
#build_image:
#  tags:
#    - docker
#  image:
#    dockerfile: Dockerfile.ci
#test:
#  tags: 
#    - shell
job:
  tags: custom-tag
    script: cat ./README.md

#    - mkdir -p ../build
#    - ls
#    - cd ../build
#    - cmake ../likelib
#    - make -j 4

