stages:
  - build
  - quality
  - test


Build:
  stage: build
  image: heshuby/prepare_build:2019-12-20
  tags:
    - docker
  script:
    - export INSTALL_DIR="/opt"
    - export PROJECT_SOURCE_DIR=${PWD}
    - export PROJECT_BUILD_DIR="./build"
    - mkdir ${PROJECT_BUILD_DIR}

    - cd ${PROJECT_BUILD_DIR}
    - cmake ${PROJECT_SOURCE_DIR} -DCMAKE_TOOLCHAIN_FILE=/opt/vcpkg/scripts/buildsystems/vcpkg.cmake
    - make -j$(nproc)
    - |
      echo
      echo -e "\033[40;1;42m =========================================================================
       ==                          Finish building                            == \n \
      ========================================================================= \033[0m"

  artifacts:
    paths:
    - build
    expire_in: 1 week


Code quality:
  stage: quality
  image: heshuby/prepare_build:2019-12-20
  tags:
    - docker
  allow_failure: true
  script:
    - cd ./src
    - export INCLUDE="-I/opt/vcpkg/installed/x64-linux/include -I${PWD} -I../build/grpc/gen -std=c++17"
    - |
      echo
      echo -e "\033[40;1;42m =========================================================================
       ==                          Start code quality                         == \n \
      ========================================================================= \033[0m"
    - clang-tidy $(find . -name "*.cpp") -header-filter=.* -- ${INCLUDE}


Unit tests:
  stage: test
  tags:
    - docker
  script:
    - |
      echo
      echo -e "\033[40;1;42m =========================================================================
       ==                          Start unit tests                                == \n \
      ========================================================================= \033[0m"

    - build/test/run_tests --log_level=test_suite --detect_memory_leaks=1 --build_info


Integration tests:
  stage: test
  tags:
    - docker
  script:
    - |
      echo
      echo -e "\033[40;1;42m =========================================================================
       ==                          Start integraion tests                                == \n \
      ========================================================================= \033[0m"

    - python3 test/integration_test/run_test.py -n build/src/node/node -r build/src/rpc-client/rpc-clientt 1


Valgrind test:
  stage: test
  image: heshuby/prepare_build:2019-12-20
  tags:
    - docker
  script:
    - |
      echo
      echo -e "\033[40;1;42m =========================================================================
       ==                          Start memory check                         == \n \
      ========================================================================= \033[0m"

    - valgrind --leak-check=full --show-leak-kinds=all build/test/run_tests --log_level=test_suite --detect_memory_leaks=1 --build_info
