stages:
  - build
  - quality
  - test

Build:
  stage: build
  image: heshuby/prepare_build:2019-12-18
  tags:
    - docker
  script: 
    - export INSTALL_DIR="/opt"
    - export PROJECT_SOURCE_DIR="/project"
    - export PROJECT_BUILD_DIR="/build"
    - mkdir ${PROJECT_BUILD_DIR}
#    - cp doc/prepare_build.sh ${INSTALL_DIR}
    - mkdir  ${PROJECT_SOURCE_DIR} && cp -r . ${PROJECT_SOURCE_DIR}

    # after soft installed
    - cd ${PROJECT_BUILD_DIR}
    - cmake ${PROJECT_SOURCE_DIR} -DCMAKE_TOOLCHAIN_FILE=/opt/vcpkg/scripts/buildsystems/vcpkg.cmake
    - make -j$(nproc)
    - echo artifacts ${PROJECT_BUILD_DIR} && ls  ${PROJECT_BUILD_DIR}
    - mkdir 1
    - touch 1/1 && touch 1/2

  artifacts:
    paths:
    - ./1/1 ./1/2
    expire_in: 1 week

    
Code quality:
  stage: quality
  tags:
    - docker
  allow_failure: true
  script:
    - echo ${INSTALL_DIR} && ls  ${INSTALL_DIR}
    - echo ${PWD} && ls 
    - export INCLUDE="-I/opt/vcpkg/installed/x64-linux/include -I${PWD} -I/build/grpc/gen -std=c++17"
    - clang-tidy node/main.cpp -- ${INCLUDE} > clang-tidy-node.log
  artifacts:
    paths:
    - clang-tidy-node.log
    expire_in: 1 week


Unit tests:
  stage: test
  tags:
    - docker
  cache: {}
  script:
    - touch unit_test.log
    - echo ${PWD} && ls
    - build/test/unit_test/run_tests --log_level=test_suite --detect_memory_leaks=1 --build_info >> unit_test.log
  artifacts:
    paths:
    - unit_test.log
    expire_in: 1 week

Integration tests:
  stage: test
  tags:
    - docker
  cache: {}
  script:
    - apt-get update && \
      apt-get install -y software-properties-common && \
      apt-get update -y && \
      apt-get install -y apt-utils && \
      apt-get dist-upgrade -y
    - apt-get install -y python3.7
    - export  TEST_FILES_DIR="/likelib"
    - mkdir ${TEST_FILES_DIR} && cd ${TEST_FILES_DIR}
    - cp build/src/node/node .
    - cp /build/src/rpc-client/rpc-client .
    - cp /project/test/integration_test test_scripts
    - python3 test_scripts/run_test.py -n ${TEST_FILES_DIR}/node -r ${TEST_FILES_DIR}/rpc-client > integration_test.log
  artifacts:
    paths:
    - integration_test.log
    expire_in: 1 week

