#image: ubuntu:19.10
#  dockerfile: Dockerfile.ci
#build_image:
#  tags:
#    - docker
#  image:
#    dockerfile: Dockerfile.ci
#test:
#  tags: 
#    - shell
docker build:
  tags: 
    - custom-tag
  script: 
     - echo $USER

#    - docker --version
#    - mkdir -p ../build
#    - ls
#    - cd ../build
#    - cmake ../likelib
#    - make -j 4

