stages:
  - build
  - quality
  - test

Build:
  stage: build
  image: heshuby/prepare_build:2019-12-18
  tags:
    - docker
  script: 
    - export INSTALL_DIR="/opt"
    - export PROJECT_SOURCE_DIR=${PWD}
    - export PROJECT_BUILD_DIR="./build"
    - mkdir ${PROJECT_BUILD_DIR}

    - cd ${PROJECT_BUILD_DIR}
    - cmake ${PROJECT_SOURCE_DIR} -DCMAKE_TOOLCHAIN_FILE=/opt/vcpkg/scripts/buildsystems/vcpkg.cmake
    - make -j$(nproc)
    - |
      echo
      echo -e "\033[40;1;42m ========================================================================= 
       ==                          Finish building                            == \n \
      ========================================================================= \033[0m"

  artifacts:
    paths:
    - build
    expire_in: 1 week

    
Code quality:
  stage: quality
  image: heshuby/prepare_build:2019-12-18
  tags:
    - docker
  allow_failure: true
  script:
    - apt update > /dev/null && apt install -y clang-tidy > /dev/null
    - cd ./src
    - export INCLUDE="-I/opt/vcpkg/installed/x64-linux/include -I${PWD} -I../build/grpc/gen -std=c++17"
    - |
      echo
      echo -e "\033[40;1;42m ========================================================================= 
       ==                          Start code quality                         == \n \
      ========================================================================= \033[0m"
    - clang-tidy $(find . -name "*.cpp") -header-filter=.* -- ${INCLUDE}


Unit tests:
  stage: test
  tags:
    - docker
  cache: {}
  script:
    - |
      echo
      echo -e "\033[40;1;42m ========================================================================= 
       ==                          Start tests                                == \n \
      ========================================================================= \033[0m"
    - build/test/run_tests --log_level=test_suite --detect_memory_leaks=1 --build_info

Valgrind test:
  stage: test
  tags:
    - docker
  script:
    - apt update > /dev/null && apt install -y valgrind > /dev/null
    - |
      echo
      echo -e "\033[40;1;42m ========================================================================= 
       ==                          Start memory check                         == \n \
      ========================================================================= \033[0m"
    - |
      valgrind --leak-check=full build/test/run_tests &&
      echo -e "\033[37;1;42m        Tests check success        \033[0m" ||
      echo -e "\033[37;1;41m        Tests check failed         \033[0m"
    - |
      valgrind --leak-check=full build/src/node/node &&
      echo -e "\033[37;1;42m        Node check success        \033[0m" || 
      echo -e "\033[37;1;41m        Node check failed         \033[0m"
    - |
      valgrind --leak-check=full build/src/rpc-client/rpc-client && 
      echo -e "\033[37;1;42m        RPC-client check success        \033[0m" || 
      echo -e "\033[37;1;41m        RPC-client check failed         \033[0m"

