Build:
  tags: 
    - custom-tag
  script: 
     - echo "Start building docker container"
     - docker build -f build.Dockerfile -t likelib2_build .
     - echo "Docker container build successfully"

Code quality:
  tags:
    - custom-tag
  image: likelib2_build
  script:
    - echo "Start checking code quality"
    - docker build -f code-quality.Dockerfile -t likelib2_code_quality .
    - echo "Docker container code quality successfuly"

Unit tests:
  tags:
    - custom-tag
  image: likelib2_build
  script:
    - echo "Start checking auto tests"
    - docker build -f test.Dockerfile -t likelib2_unit_test .
    - echo "Docker container auto tests successfuly"

#Integration tests:
#  tags:
#    - custom-tag
#  script:
#    - echo "Start checking integration tests"
#    - docker build -f test.Dockerfile -t likelib2_integration_test .
#    - echo "Docker container integration tests successfuly"
