Build:
  tags: 
    - custom-tag
  script: 
     - echo "Start building docker container"
     - docker build -f Dockerfile.build -t likelib2_build .
     - echo "Docker container build successfully"
#  artifacts:
#    - build

Code quality:
  tags:
    - custom-tag
  script:
    - echo "Start checking code quality"
    - docker build -f Dockerfile.code-quality -t likelib2_code_quality .
    - echo "Docker container code quality successfuly"

Tests:
  tags:
    - custom-tag
  script:
    - echo "Start checking auto tests"
    - docker build -f Dockerfile.test -t likelib2_test .
    - echo "Docker container auto tests successfuly"
