stages:
  - build
  - unit-tests
  - integration-tests
  - analyzers


Build:
  stage: build
  image: heshuby/prepare_build:2020-02-07
  tags:
    - docker
  script:
    - INSTALL_DIR="/opt"
    - SOURCE_DIR=${PWD}
    - BUILD_DIR="${PWD}/build"
    - mkdir -p ${BUILD_DIR}
    - cmake -DCMAKE_BUILD_TYPE=Release -S ${SOURCE_DIR} -B ${BUILD_DIR}
    - cd ${BUILD_DIR} && make -j$(nproc)
    - |
      echo
      echo -e "\033[40;1;42m ========================================================================= 
       ==                          Finish building                            == \n \
      ========================================================================= \033[0m"
  artifacts:
    paths:
      - build
    expire_in: 1 week



Code quality:
  stage: analyzers
  image: heshuby/prepare_build:2020-02-07
  tags:
    - docker
  script:
    - INSTALL_DIR="/opt"
    - SOURCE_DIR=${PWD}
    - LOG_DIR=${PWD}/clang-tidy-log
    - BUILD_DIR="${PWD}/build"
    - mkdir -p ${LOG_DIR}
    - mkdir -p ${BUILD_DIR}
    - mkdir -p /tmp/logs
    - cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_CXX_CLANG_TIDY="${SOURCE_DIR}/cmake/clang-tidy.py;-header-filter=.*;" -S ${SOURCE_DIR} -B ${BUILD_DIR}
    - cd ${BUILD_DIR} && make || (cp /tmp/logs/* ${LOG_DIR} && exit 1)
    - cp /tmp/logs/* ${LOG_DIR} && cat ${LOG_DIR}/clang-tidy-output.txt
    - test -f /tmp/logs/.error-flag && exit 1
    - |
      echo
      echo -e "\033[40;1;42m ========================================================================= 
       ==                          Finish code quality                        == \n \
      ========================================================================= \033[0m"
  artifacts:
    when: always
    paths:
      - clang-tidy-log
    expire_in: 1 week



Unit tests:
  stage: unit-tests
  tags:
    - docker
  script:
    - |
      echo
      echo -e "\033[40;1;42m =========================================================================
       ==                          Start unit tests                           == \n \
      ========================================================================= \033[0m"
    - build/bin/run_tests --log_level=test_suite --detect_memory_leaks=1 --build_info


Integration tests:
  timeout: 25m
  stage: integration-tests
  image: heshuby/prepare_build:2020-02-07
  tags:
    - docker
  script:
    - |
      echo
      echo -e "\033[40;1;42m ========================================================================= 
       ==                          Start integration tests                    == \n \
      ========================================================================= \033[0m"
    - PROJECT_SOURCE_DIR=${PWD}
    - TEST_DIR="intergation_test_run"
    - mkdir ${TEST_DIR}
    - cd ${TEST_DIR}
    - python3 ${PROJECT_SOURCE_DIR}/test/integration_test/run_test.py -n ${PROJECT_SOURCE_DIR}/build/bin/node -r ${PROJECT_SOURCE_DIR}/build/bin/rpc-client
  artifacts:
    when: always
    paths:
      - intergation_test_run
    expire_in: 1 week

Valgrind test:
  stage: analyzers
  image: heshuby/prepare_build:2020-02-07
  tags:
    - docker
  script:
    - |
      echo
      echo -e "\033[40;1;42m ========================================================================= 
       ==                          Start memory check                         == \n \
      ========================================================================= \033[0m"
    - valgrind --leak-check=full --error-exitcode=1 --show-leak-kinds=all build/bin/run_tests --log_level=test_suite --detect_memory_leaks=1 --build_info
