
image: ubuntu:19.10
stages:
  - create
  - ls
tags:
  - docker
Creating files:
  stage: create
  script: 
     - echo "Start create container"
     - mkdir build
     - touch ./build/1
     - touch ./build/2
     - echo "Docker container create successfully"
  artifacts:
    paths:
      - build

View files:
  stage: ls
  script:
    - ls -l
    - ls ./build -l
