# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import public_rpc_pb2 as public__rpc__pb2


class NodeStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.balance = channel.unary_unary(
        '/Likelib.Node/balance',
        request_serializer=public__rpc__pb2.Address.SerializeToString,
        response_deserializer=public__rpc__pb2.Money.FromString,
        )
    self.transaction = channel.unary_unary(
        '/Likelib.Node/transaction',
        request_serializer=public__rpc__pb2.Transaction.SerializeToString,
        response_deserializer=public__rpc__pb2.Hash.FromString,
        )


class NodeServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def balance(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def transaction(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_NodeServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'balance': grpc.unary_unary_rpc_method_handler(
          servicer.balance,
          request_deserializer=public__rpc__pb2.Address.FromString,
          response_serializer=public__rpc__pb2.Money.SerializeToString,
      ),
      'transaction': grpc.unary_unary_rpc_method_handler(
          servicer.transaction,
          request_deserializer=public__rpc__pb2.Transaction.FromString,
          response_serializer=public__rpc__pb2.Hash.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'Likelib.Node', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
