# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: public_rpc.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='public_rpc.proto',
  package='Likelib',
  syntax='proto3',
  serialized_options=_b('\n\025by.heshu.likelib.nodeB\020LikelibNodeProtoP\001\242\002\003HLW'),
  serialized_pb=_b('\n\x10public_rpc.proto\x12\x07Likelib\"{\n\x0bTransaction\x12\x1e\n\x06\x61mount\x18\x01 \x01(\x0b\x32\x0e.Likelib.Money\x12&\n\x0c\x66rom_address\x18\x02 \x01(\x0b\x32\x10.Likelib.Address\x12$\n\nto_address\x18\x03 \x01(\x0b\x32\x10.Likelib.Address\"\x1a\n\x07\x41\x64\x64ress\x12\x0f\n\x07\x61\x64\x64ress\x18\x01 \x01(\t\"\x1b\n\x04Hash\x12\x13\n\x0bhash_string\x18\x01 \x01(\t\"\x16\n\x05Money\x12\r\n\x05money\x18\x01 \x01(\x04\x32k\n\x04Node\x12-\n\x07\x62\x61lance\x12\x10.Likelib.Address\x1a\x0e.Likelib.Money\"\x00\x12\x34\n\x0btransaction\x12\x14.Likelib.Transaction\x1a\r.Likelib.Hash\"\x00\x42\x31\n\x15\x62y.heshu.likelib.nodeB\x10LikelibNodeProtoP\x01\xa2\x02\x03HLWb\x06proto3')
)




_TRANSACTION = _descriptor.Descriptor(
  name='Transaction',
  full_name='Likelib.Transaction',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='amount', full_name='Likelib.Transaction.amount', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='from_address', full_name='Likelib.Transaction.from_address', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='to_address', full_name='Likelib.Transaction.to_address', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=29,
  serialized_end=152,
)


_ADDRESS = _descriptor.Descriptor(
  name='Address',
  full_name='Likelib.Address',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='address', full_name='Likelib.Address.address', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=154,
  serialized_end=180,
)


_HASH = _descriptor.Descriptor(
  name='Hash',
  full_name='Likelib.Hash',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='hash_string', full_name='Likelib.Hash.hash_string', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=182,
  serialized_end=209,
)


_MONEY = _descriptor.Descriptor(
  name='Money',
  full_name='Likelib.Money',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='money', full_name='Likelib.Money.money', index=0,
      number=1, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=211,
  serialized_end=233,
)

_TRANSACTION.fields_by_name['amount'].message_type = _MONEY
_TRANSACTION.fields_by_name['from_address'].message_type = _ADDRESS
_TRANSACTION.fields_by_name['to_address'].message_type = _ADDRESS
DESCRIPTOR.message_types_by_name['Transaction'] = _TRANSACTION
DESCRIPTOR.message_types_by_name['Address'] = _ADDRESS
DESCRIPTOR.message_types_by_name['Hash'] = _HASH
DESCRIPTOR.message_types_by_name['Money'] = _MONEY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Transaction = _reflection.GeneratedProtocolMessageType('Transaction', (_message.Message,), {
  'DESCRIPTOR' : _TRANSACTION,
  '__module__' : 'public_rpc_pb2'
  # @@protoc_insertion_point(class_scope:Likelib.Transaction)
  })
_sym_db.RegisterMessage(Transaction)

Address = _reflection.GeneratedProtocolMessageType('Address', (_message.Message,), {
  'DESCRIPTOR' : _ADDRESS,
  '__module__' : 'public_rpc_pb2'
  # @@protoc_insertion_point(class_scope:Likelib.Address)
  })
_sym_db.RegisterMessage(Address)

Hash = _reflection.GeneratedProtocolMessageType('Hash', (_message.Message,), {
  'DESCRIPTOR' : _HASH,
  '__module__' : 'public_rpc_pb2'
  # @@protoc_insertion_point(class_scope:Likelib.Hash)
  })
_sym_db.RegisterMessage(Hash)

Money = _reflection.GeneratedProtocolMessageType('Money', (_message.Message,), {
  'DESCRIPTOR' : _MONEY,
  '__module__' : 'public_rpc_pb2'
  # @@protoc_insertion_point(class_scope:Likelib.Money)
  })
_sym_db.RegisterMessage(Money)


DESCRIPTOR._options = None

_NODE = _descriptor.ServiceDescriptor(
  name='Node',
  full_name='Likelib.Node',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=235,
  serialized_end=342,
  methods=[
  _descriptor.MethodDescriptor(
    name='balance',
    full_name='Likelib.Node.balance',
    index=0,
    containing_service=None,
    input_type=_ADDRESS,
    output_type=_MONEY,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='transaction',
    full_name='Likelib.Node.transaction',
    index=1,
    containing_service=None,
    input_type=_TRANSACTION,
    output_type=_HASH,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_NODE)

DESCRIPTOR.services_by_name['Node'] = _NODE

# @@protoc_insertion_point(module_scope)
